{{ $dataNew->nama }} <br>
{{ $dataNew->jk }} <br>
{{ $dataNew->nik }} <br>
{{ $dataNew->no_kk }} <br>
{{ $dataNew->tempat_lahir }} <br>
{{ $dataNew->tanggal_lahir }} <br>
{{ $dataNew->agama }} <br>
{{ $dataNew->negara }} <br>
{{ $dataNew->kebutuhan_khusus }} <br>
{{ $dataNew->alamat }} <br>
{{ $dataNew->rt }} <br>
{{ $dataNew->rw }} <br>
{{ $dataNew->dusun }} <br>
{{ $dataNew->kelurahan }} <br>
{{ $dataNew->kecamatan }} <br>
{{ $dataNew->kota }} <br>
{{ $dataNew->provinsi }} <br>
{{ $dataNew->kode_pos }} <br>
{{ $dataNew->lintang }} <br>
{{ $dataNew->bujur }} <br>
{{ $dataNew->jenis_tinggal }} <br>
{{ $dataNew->alat_transportasi }} <br>
{{ $dataNew->anak_ke }} <br>
{{ $dataNew->jumlah_saudara_kandung }} <br>
{{ $dataNew->nama_ayah }} <br>
{{ $dataNew->nik_ayah }} <br>
{{ $dataNew->tanggal_lahir_ayah }} <br>
{{ $dataNew->pendidikan_ayah }} <br>
{{ $dataNew->pekerjaan_ayah }} <br>
{{ $dataNew->penghasilan_ayah }} <br>
{{ $dataNew->hp_ayah }} <br>
{{ $dataNew->nama_ibu }} <br>
{{ $dataNew->nik_ibu }} <br>
{{ $dataNew->tanggal_lahir_ibu }} <br>
{{ $dataNew->pendidikan_ibu }} <br>
{{ $dataNew->pekerjaan_ibu }} <br>
{{ $dataNew->penghasilan_ibu }} <br>
{{ $dataNew->hp_ibu }} <br>
{{ $dataNew->nama_wali }} <br>
{{ $dataNew->nik_wali }} <br>
{{ $dataNew->tanggal_lahir_wali }} <br>
{{ $dataNew->pendidikan_wali }} <br>
{{ $dataNew->pekerjaan_wali }} <br>
{{ $dataNew->penghasilan_wali }} <br>
{{ $dataNew->hp_wali }} <br>
