{{ $dataOld->nama }} <br>
{{ $dataOld->jk }} <br>
{{ $dataOld->nik }} <br>
{{ $dataOld->no_kk }} <br>
{{ $dataOld->tempat_lahir }} <br>
{{ $dataOld->tanggal_lahir }} <br>
{{ $dataOld->agama }} <br>
{{ $dataOld->negara }} <br>
{{ $dataOld->kebutuhan_khusus }} <br>
{{ $dataOld->alamat }} <br>
{{ $dataOld->rt }} <br>
{{ $dataOld->rw }} <br>
{{ $dataOld->dusun }} <br>
{{ $dataOld->kelurahan }} <br>
{{ $dataOld->kecamatan }} <br>
{{ $dataOld->kota }} <br>
{{ $dataOld->provinsi }} <br>
{{ $dataOld->kode_pos }} <br>
{{ $dataOld->lintang }} <br>
{{ $dataOld->bujur }} <br>
{{ $dataOld->jenis_tinggal }} <br>
{{ $dataOld->alat_transportasi }} <br>
{{ $dataOld->anak_ke }} <br>
{{ $dataOld->jumlah_saudara_kandung }} <br>
{{ $dataOld->nama_ayah }} <br>
{{ $dataOld->nik_ayah }} <br>
{{ $dataOld->tanggal_lahir_ayah }} <br>
{{ $dataOld->pendidikan_ayah }} <br>
{{ $dataOld->pekerjaan_ayah }} <br>
{{ $dataOld->penghasilan_ayah }} <br>
{{ $dataOld->hp_ayah }} <br>
{{ $dataOld->nama_ibu }} <br>
{{ $dataOld->nik_ibu }} <br>
{{ $dataOld->tanggal_lahir_ibu }} <br>
{{ $dataOld->pendidikan_ibu }} <br>
{{ $dataOld->pekerjaan_ibu }} <br>
{{ $dataOld->penghasilan_ibu }} <br>
{{ $dataOld->hp_ibu }} <br>
{{ $dataOld->nama_wali }} <br>
{{ $dataOld->nik_wali }} <br>
{{ $dataOld->tanggal_lahir_wali }} <br>
{{ $dataOld->pendidikan_wali }} <br>
{{ $dataOld->pekerjaan_wali }} <br>
{{ $dataOld->penghasilan_wali }} <br>
{{ $dataOld->hp_wali }} <br>
